package com.agrofront.agrohelper.domain

data class DroneModel(
    val id: String,
    val manufacturer: String,
    val name: String,
    val photoUrl: String,
    val rotorLayout: String,
    val sprayTankLiters: Double,
    val sprayPayloadKg: Double,
    val spreadTankLiters: Double?,
    val spreadPayloadKg: Double?,
    val maxLiquidFlowLMin: Double?,
    val sprayWidthMeters: String,
    val dropletSizeMicrons: String?,
    val nozzleSystem: String,
    val aircraftWeightKg: String,
    val dimensions: String,
    val protectionRating: String?,
    val maxSpeedMps: Double?,
    val maxFlightDistance: String?,
    val positioning: String?,
    val obstacleAvoidance: String?,
    val terrainFollowing: String?,
    val motorSystem: String?,
    val propellerSystem: String?,
    val battery: String?,
    val batteryCapacity: String?,
    val charger: String?,
    val chargeTime: String?,
    val productivity: String?,
    val spreading: String?,
    val operatingTemperature: String?,
    val notes: String,
    val sourceLabel: String,
    val verified: String
)

object DroneCatalog {
    val models: List<DroneModel> = listOf(
        DroneModel(
            id = "dji-t25",
            manufacturer = "DJI",
            name = "AGRAS T25",
            photoUrl = "https://www.ruralautomation.com.au/cdn/shop/files/T25_45_FrontView.png?v=1713755136&width=1946",
            rotorLayout = "4 ротора",
            sprayTankLiters = 20.0,
            sprayPayloadKg = 20.0,
            spreadTankLiters = 35.0,
            spreadPayloadKg = 25.0,
            maxLiquidFlowLMin = 16.0,
            sprayWidthMeters = "4–7 м",
            dropletSizeMicrons = "50–500 мкм",
            nozzleSystem = "2 центробежных атомизирующих распылителя LX8060SZ",
            aircraftWeightKg = "25,4 кг без АКБ / 32 кг с АКБ",
            dimensions = "2585×2675×780 мм в рабочем виде; 1050×690×820 мм полностью сложен",
            protectionRating = null,
            maxSpeedMps = null,
            maxFlightDistance = "настраиваемый радиус до 2000 м",
            positioning = "RTK: ±10 см по горизонтали и вертикали при хорошем сигнале",
            obstacleAvoidance = "многонаправленное обнаружение препятствий 1–50 м",
            terrainFollowing = "следование рельефу, рабочий диапазон стабилизации 1,5–30 м",
            motorSystem = "4 двигателя, 4600 Вт на ротор",
            propellerSystem = "4 пропеллера, 50 дюймов",
            battery = "интеллектуальная полётная батарея DJI",
            batteryCapacity = null,
            charger = null,
            chargeTime = null,
            productivity = null,
            spreading = "35 л / 25 кг; рекомендуемая ширина внесения 5–8 м",
            operatingTemperature = null,
            notes = "Компактная платформа для опрыскивания и внесения гранул. Максимальный поток 16 л/мин со штатными двумя распылителями и до 24 л/мин при четырёх.",
            sourceLabel = "DJI AGRAS T25 — официальные Specs",
            verified = "09.2026"
        ),
        DroneModel(
            id = "dji-t50",
            manufacturer = "DJI",
            name = "AGRAS T50",
            photoUrl = "https://static.wixstatic.com/media/ce600a_8ea045773a914c9798b9943c8b96ebca~mv2.jpg/v1/fill/w_480%2Ch_480%2Cal_c%2Cq_80%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/ce600a_8ea045773a914c9798b9943c8b96ebca~mv2.jpg",
            rotorLayout = "8 пропеллеров, коаксиальная двухроторная схема",
            sprayTankLiters = 40.0,
            sprayPayloadKg = 40.0,
            spreadTankLiters = 75.0,
            spreadPayloadKg = 50.0,
            maxLiquidFlowLMin = 16.0,
            sprayWidthMeters = "4–11 м",
            dropletSizeMicrons = "50–500 мкм",
            nozzleSystem = "2 центробежных атомизирующих распылителя LX8060SZ",
            aircraftWeightKg = "39,9 кг без АКБ / 52 кг с АКБ",
            dimensions = "2800×3085×820 мм в рабочем виде; 1115×750×900 мм полностью сложен",
            protectionRating = null,
            maxSpeedMps = null,
            maxFlightDistance = "настраиваемый радиус до 2000 м",
            positioning = "RTK: ±10 см по горизонтали и вертикали при хорошем сигнале",
            obstacleAvoidance = "фазированные радары; многонаправленное обнаружение 1–50 м",
            terrainFollowing = "определение высоты 1–50 м; стабилизация 1,5–30 м",
            motorSystem = "8 роторов, 4000 Вт на ротор",
            propellerSystem = "8 пропеллеров, 54 дюйма",
            battery = "интеллектуальная полётная батарея DJI",
            batteryCapacity = null,
            charger = null,
            chargeTime = null,
            productivity = null,
            spreading = "75 л / 50 кг; ширина внесения до 8 м",
            operatingTemperature = null,
            notes = "Тяжёлая платформа для опрыскивания и внесения гранул. Максимальный поток 16 л/мин со штатными двумя распылителями и до 24 л/мин при четырёх.",
            sourceLabel = "DJI AGRAS T50 — официальные Specs",
            verified = "09.2026"
        ),
        DroneModel(
            id = "xag-p100-pro",
            manufacturer = "XAG",
            name = "P100 Pro",
            photoUrl = "https://droneval.com/11863-thickbox_default/xag-p100-pro.jpg",
            rotorLayout = "4 ротора",
            sprayTankLiters = 50.0,
            sprayPayloadKg = 50.0,
            spreadTankLiters = 80.0,
            spreadPayloadKg = 50.0,
            maxLiquidFlowLMin = 22.0,
            sprayWidthMeters = "5–10 м",
            dropletSizeMicrons = "60–400 мкм",
            nozzleSystem = "RevoSpray 3: 2 роторных атомизирующих распылителя, 1000–16000 об/мин",
            aircraftWeightKg = "46 кг, платформа с АКБ без модуля полезной нагрузки",
            dimensions = "2927×2868×323 мм развёрнут; 893×1095×345 мм сложен",
            protectionRating = "IPX6K",
            maxSpeedMps = 13.8,
            maxFlightDistance = "до 2000 м",
            positioning = "RTK: ±10 см; без RTK: ±0,6 м горизонтально / ±0,3 м вертикально",
            obstacleAvoidance = "4D-радар RD24912: 1,5–80 м; безопасное торможение до относительной скорости 13,8 м/с",
            terrainFollowing = "радар TR24S100: измерение 0,5–100 м, удержание высоты 1–30 м, склон до 45° при ≤2 м/с",
            motorSystem = "A50, 4100 Вт каждый, максимальная тяга 52 кг на двигатель",
            propellerSystem = "складные 5515, 55×15 дюймов",
            battery = "Smart SuperCharge Battery B13960S, 13S LiPo",
            batteryCapacity = "20 000 мА·ч / 962 Вт·ч; 48,1 В / 120 А",
            charger = "CM13600: до 3400 Вт при 220–240 В; GC4000+ до 5,1 кВт",
            chargeTime = "около 11 мин в режиме SuperCharge по данным XAG; зависит от температуры и зарядной системы",
            productivity = "официальные примеры: до 19 га/ч при 30 л/га на пшенице; до 28 га/ч при 12 л/га на рисе; фактическая зависит от условий",
            spreading = "RevoCast 3: 80 л / 50 кг; до 150 кг/мин; гранулы 1–6 мм; ширина 3–7 м",
            operatingTemperature = "0…40 °C",
            notes = "P100 Pro поддерживает полностью автономные маршруты, возврат при низком заряде или уровне материала и продолжение операции. Есть FPV 1080p, система RealTerra 2 для картографирования и возможность работы без интернета через локальную RC-сеть с виртуальным RTK.",
            sourceLabel = "XAG P100 Pro — официальные Specs и product page",
            verified = "09.2026"
        ),
        DroneModel(
            id = "xag-p150",
            manufacturer = "XAG",
            name = "P150",
            photoUrl = "https://xag.com.py/media/p150/drone-xag-p150.png",
            rotorLayout = "4 ротора",
            sprayTankLiters = 60.0,
            sprayPayloadKg = 70.0,
            spreadTankLiters = 115.0,
            spreadPayloadKg = 70.0,
            maxLiquidFlowLMin = 30.0,
            sprayWidthMeters = "5–10 м",
            dropletSizeMicrons = "60–500 мкм",
            nozzleSystem = "RevoSpray 4: 2 центробежных распылителя, 1500–16000 об/мин",
            aircraftWeightKg = "54 кг с RevoSpray 4 и АКБ; 58 кг с RevoCast 4 и АКБ",
            dimensions = "3110×3118×764 мм развёрнут; 1072×1102×788 мм сложен с RevoSpray 4",
            protectionRating = "IPX6K",
            maxSpeedMps = 18.0,
            maxFlightDistance = "до 2000 м",
            positioning = "RTK: ±10 см; без RTK: ±0,6 м горизонтально / ±0,3 м вертикально",
            obstacleAvoidance = "4D-радар RD2488: 1,5–100 м; безопасная относительная скорость обхода до 13,8 м/с",
            terrainFollowing = "радар TR24S100_24: 0,5–100 м; удержание 1–30 м; склон до 45° при ≤2 м/с",
            motorSystem = "A55, 4700 Вт каждый, максимальная тяга 55 кг на двигатель",
            propellerSystem = "складные карбоновые пропеллеры диаметром 1530 мм",
            battery = "Smart Supercharge Battery M1PPA13970BH, Li-ion polymer",
            batteryCapacity = "20 000 мА·ч; 48,75 В / 140 А; максимальный зарядный ток 100 А",
            charger = "CM13600BH; GC4000+ 3400 Вт номинально / до 5100 Вт",
            chargeTime = "быстрая зарядка зависит от источника питания и охлаждения",
            productivity = "зависит от нормы, ширины и скорости; аппарат рассчитан на высокопроизводительную обработку больших площадей",
            spreading = "RevoCast 4: 115 л / 70 кг; до 280 кг/мин; гранулы 1–10 мм; ширина 3–8 м",
            operatingTemperature = "0…40 °C",
            notes = "RevoSpray 4 имеет номинальный бак 60 л и максимальную ёмкость 70 л. Два гибких крыльчатых насоса дают до 30 л/мин. FPV: 1080p/30 fps, передняя и нижняя камеры. RealTerra 3 оснащён 12-Мп камерой. Максимальная скорость платформы — 18 м/с, но при активном обходе препятствий XAG указывает безопасный предел относительной скорости до 13,8 м/с.",
            sourceLabel = "XAG P150 — официальные Specs и product page",
            verified = "09.2026"
        ),
        DroneModel(
            id = "hd-540-pro",
            manufacturer = "HD / Huida Tech",
            name = "HD540Pro",
            photoUrl = "https://loja.superimportadora.com.br/wp-content/uploads/2024/03/huida-hd540-pro.jpg",
            rotorLayout = "6 роторов",
            sprayTankLiters = 40.0,
            sprayPayloadKg = 40.0,
            spreadTankLiters = 60.0,
            spreadPayloadKg = 50.0,
            maxLiquidFlowLMin = 14.0,
            sprayWidthMeters = "10–12 м в материалах разных поставщиков",
            dropletSizeMicrons = "50–500 мкм",
            nozzleSystem = "4 центробежных распылителя",
            aircraftWeightKg = "около 34 кг без полезной нагрузки по техлистам HD540Pro",
            dimensions = "3050×2940×830 мм развёрнут; сложенная транспортная конфигурация зависит от ревизии",
            protectionRating = "IP65 у ряда актуальных комплектаций/поставок",
            maxSpeedMps = null,
            maxFlightDistance = "видеолиния >1,5 км по техлистам",
            positioning = "RTK: ±10 см горизонтально и вертикально; радарная высота около ±0,1 м",
            obstacleAvoidance = "360° вращающийся радар; диапазон обнаружения препятствий 1–30 м",
            terrainFollowing = "поддержка следования рельефу; диапазон удержания высоты 1–30 м",
            motorSystem = "шестиосная/шестироторная платформа",
            propellerSystem = "6 роторов; геометрия и тип пропеллеров зависят от ревизии",
            battery = "Smart Battery 18S",
            batteryCapacity = "68,4 В / 30 000 мА·ч / около 2,1 кВт·ч; масса АКБ около 13 кг по техлисту",
            charger = "поддерживаются мощные зарядные системы 220/380 В; встречаются конфигурации до 8 кВт",
            chargeTime = "примерно 9 мин с 30% до 90% по Vector Agr; в других техлистах 20–95% около 9–13 мин",
            productivity = "до 22 га/ч / около 330 му/ч в рекламно-технических материалах; реальная производительность зависит от нормы и условий",
            spreading = "60 л / 50 кг; заявленная скорость внесения до 110 кг/мин",
            operatingTemperature = null,
            notes = "HD540Pro совмещает опрыскивание и разбрасывание. Для опрыскивания заявлены 4 центробежных форсунки, поток до 14 л/мин и капля 50–500 мкм. В техлистах также встречаются: 8,5 мин висения с полной нагрузкой при опрыскивании, 7 мин при разбрасывании и до 18 мин без нагрузки. У модели существуют разные ревизии и региональные комплектации, поэтому значения 10/11/12 м по ширине распыла и 9/13 мин по зарядке могут различаться.",
            sourceLabel = "Huida Tech / Vector Agr HD540Pro и региональные техлисты",
            verified = "09.2026"
        )
    )

    val manufacturers: List<String> = listOf("Все", "DJI", "XAG", "HD / Huida Tech")
}
